services:
  server:
    build: ./server
    container_name: server
    ports:
      - 3000:3000
  client:
    build: ./client
    container_name: client
    ports:
      - 1234:1234
  postgres:
    image: "postgres:16.3-alpine"
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5433
    environment:
      - POSTGRES_DB=contacts
      - POSTGRES_USER=von
      - POSTGRES_PASSWORD=von

volumes:
  postgres-data: